# Description: A lightweight Shopify CLI container intended for CI, based on ruby:3-alpine
# Usage: docker build -f Dockerfile-v2_32_0 -t shine09/shopify-cli .

FROM ruby:3-alpine
RUN test -n "2.32.0"
# Install deps for native gem installation, sudo and bash for the Shopify gem
RUN apk update && apk add --virtual build-dependencies build-base gcompat sudo bash npm
RUN gem install shopify-cli -v 2.32.0
RUN shopify reporting off
